Feature
brahimdidi/live-soccer-games pull request #2
Opened 2022-06-30 21:01 UTC by brahimdidi

2022-06-30 22:32 UTC, mateo951 requested changes
### Hi @brahimdidi, 

📝👌 **Your project highlights** 😎 
- General Requirements 💪🤓
- Video Presentation ✔ Big fan of football 🤓 
- App is working as expected 😎

Excellent job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-30 22:32 UTC, mateo951 commented on README.md
> +- Open terminal and clone the project: `git clone git@github.com:brahimdidi/live-soccer-games`
Please be sure to fix this instruction because right now it's now working properly 🧐

- git clone git@github.com:brahimdidi/live-soccer-games ✖
- git clone git@github.com:brahimdidi/live-soccer-games.git ✔

2022-06-30 22:32 UTC, mateo951 commented on README.md
> +- [live](https://footlive.netlify.app/)
Kindly make sure that your app is live using Heroku, Netlify, or GitHub Pages. Right now the link is broken 😥

2022-06-30 22:32 UTC, mateo951 commented on README.md
> +## Acknowledgments
Don't forget to give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/) 🤓

2022-06-30 22:32 UTC, mateo951 commented on src/App.js
> +    </Routes>
The project contains a Home page and a Detail page 🤓 Well done!

2022-06-30 22:32 UTC, mateo951 commented on src/App.js
> +import { Routes, Route } from 'react-router-dom';
You successfully created a single page application (SPA) using react-router-dom to serve each page without reloading 🙌🔥

2022-06-30 22:32 UTC, mateo951 commented on src/components/tests/AllGames.test.js
> +      <Provider store={store}>
The project uses Redux for state management and data retrieved from the API are stored in the Redux store correctly 😉 Fantastic job!

2022-07-01 09:02 UTC, rustam-tolipov approved these changes
## Hi @brahimdidi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-01 20:51 UTC, merged